add release policy
Backbase/local-backend-setup pull request #9
Opened 2023-08-31 13:46 UTC by miladbb

2023-08-31 14:14 UTC, bbzurek submitted a review, later dismissed

2023-09-01 14:22 UTC, sindhuashwath requested changes

2023-09-01 14:22 UTC, sindhuashwath commented on README.md
> +We release this repository for every Backbase LTS release. Each LTS release is compatible with all the Backbase versions down to the previous LTS version. For example, with the `2022.02-LTS` release,
We release this repository after every Backbase Breaking Changes release. Each release is compatible with all the Backbase versions until its next LTS version.
For example, with the `2022.03` release, you can use any Backbase version <ins>Higher</ins> than `2022.03` up to `2023.09-LTS`.

2023-09-01 14:55 UTC, sindhuashwath approved these changes

2023-09-04 07:49 UTC, merged